### ISSUE TITLE
Add unit tests for the playlist panel

### ISSUE THREAD

**Issue by agersant** [agersant/polaris-web#12]
See CONTRIBUTING.md for getting started, and test/collection.js for an example of a test suite. For the playlist panel, key features to test are:

- Clicking songs in the collection add them the playlist panel
- Clicking 'Queue All' in the collection adds the relevant tracks to the palylist panel
- Clicking a track in the playlist panel highlights it and pushes its title to the player panel

**Comment by egdbear** [comment]
Hey, i am willing to do it! :smile:  also #11

**Comment by agersant** [comment]
Awesome, let me know if you need any help!

**Comment by agersant** [comment]
Added in fb0bdf71ce45cb5f4f37b454fe620161adb83ff8
