### ISSUE TITLE
Playlist sort order combo is misaligned

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris-web#31]
![image](https://user-images.githubusercontent.com/308347/62778098-17f21280-bab8-11e9-9992-3002e87bf84d.png)

Tested with Firefox/Linux.

**Comment by lnicola** [comment]
Still misaligned in Chrome, but less bad:

![image](https://user-images.githubusercontent.com/308347/62778142-440d9380-bab8-11e9-9078-d8d46b56da06.png)

**Comment by agersant** [comment]
I took a look at this in both browsers and it looked significantly more correct than on your screenshots. What OS is this happening on?

**Comment by agersant** [comment]
I think I found a good fix. I committed it as a009f9a4fb0b9a87edec43e46f74ced85e232781 - can you tell me if this resolves the issue for you?
In case you forgot how to test this, use the `-w` flag of Polaris to make it serve a copy of `polaris-web` with this change in it.

**Comment by lnicola** [comment]
Thanks, works fine now:

![image](https://user-images.githubusercontent.com/308347/71880456-11d09280-3139-11ea-834c-aab97bc66a98.png)

![image](https://user-images.githubusercontent.com/308347/71880469-185f0a00-3139-11ea-9c25-98f25d7b6c1d.png)
