### ISSUE TITLE
MediaSession support

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris-web#33]
This would be nice to have, see https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API.

**Comment by agersant** [comment]
This looks very easy to implement, great suggestion!

**Comment by agersant** [comment]
Added in 815db0e8aa4e1fd7205d1479272417ee6eb554ae
I tested the functionality in Chrome Android. Song info, covert art, and playback controls are working. 
Playback progress looks fairly broken but the relevant API method isn't implemented yet (https://www.chromestatus.com/feature/5677548182700032). I still added a call to it for when the day comes.

**Comment by lnicola** [comment]
Playback is totally broken for me in Chromium 79 because of that change:

```
Uncaught TypeError: Failed to construct 'MediaMetadata': required member src is undefined.
    at re.<anonymous> (tags/player.tag.js:17)
    at re.<anonymous> (tags/player.tag.js:35)
    at Object.value (riot%2Bcompiler.min.js:2)
    at re.<anonymous> (tags/playlist.tag.js:136)
    at re.<anonymous> (tags/playlist.tag.js:148)
    at re.A (riot%2Bcompiler.min.js:2)
```

**Comment by agersant** [comment]
Nice catch. Are you trying to play a track that doesn't have an album cover by any chance?

**Comment by lnicola** [comment]
I assume it's undefined. I tried with multiple tracks and none of them worked, but it's possible that they don't have a cover.

**Comment by agersant** [comment]
Should be fixed with feeec8b2f5bc265f8749aee45889a46c777f540a

**Comment by lnicola** [comment]
I can confirm, it's working now. Tested in Chrome/Android because Chromium doesn't seem to support the API on Linux.

**Comment by agersant** [comment]
Thanks
