### ISSUE TITLE
Breadcrumb text is not centered on Linux and Android

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris-web#41]
I realize this is a bit nitpicky, but..

![image](https://user-images.githubusercontent.com/308347/72749578-1da16780-3bc3-11ea-979c-00a29188a28c.png)

Happens in both Firefox and Chromium on Linux and at least Fenix on Android. The font is Hind (as expected).

**Comment by agersant** [comment]
I've been playing wack-a-mole with this widget for a bit, I think it depends on the underlying text rendering code being used. It looks great on Windows+Firefox for example:

![image](https://user-images.githubusercontent.com/817256/72757891-0728eb00-3b86-11ea-8ed1-5d6b0dbd826a.png)

Probably fixable though!

**Comment by lnicola** [comment]
Fixed in the Vue version:

![image](https://user-images.githubusercontent.com/308347/73604654-fbcdba80-459c-11ea-9998-7679ea4d8d82.png)

**Comment by agersant** [comment]
Makes no sense at all but I'm not going to complain!
