### ISSUE TITLE
Back navigation in the Browse tab loses scroll position

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris-web#42]
When in browse mode with a long list of directories, if you scroll down and click on one of them, then hit back (either in the browser or using the breadcrumb), the scroll position is lost.

Again, this is a bit of a nitpick and probably very hard to fix. I really like Polaris, no matter how many issues I keep opening :smile:.

**Comment by agersant** [comment]
Your issues are useful and actionable so please keep them coming! I'm also always happy to see I'm not the only active user of the project.

This one seems to be a fairly well documented topic (I just googled `SPA scroll position`) so I can probably do something about it.

**Comment by agersant** [comment]
Fixed in 4182b0d0f52f84fa0b25abde086ae20eb2c7ebcf!
