### ISSUE TITLE
Bug with adding new music source

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#52]
Polaris 0.12.2
Windows 10, Firefox, Edge (old and new)

It is probably similar to the bug in comments of #50.
Basically clicking "Add more" causes reloading of the page. After that everything works as expected.

**Comment by michalsieron** [comment]
Seems that the same is for adding new user. Possibly there are more buttons that are working that way.

**Comment by agersant** [comment]
Thanks for the report. Fixed here: https://github.com/agersant/polaris-web/pull/55
