### ISSUE TITLE
Bug with adding folders to queue

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#53]
Polaris 0.12.2
Windows 10, Firefox, Edge (old and new)

Assume following folder tree:

Music:
  - Test1:
    - song11.mp3
    - song12.mp3
    - song13.mp3
    - ...
  - Test1 2nd folder:
    - song21.mp3
    - song22.mp3
    - song23.mp3
    - ...
  - Test13rd folder:
    - song31.mp3
    - song32.mp3
    - song33.mp3
    - ...

What matters is that there are several folders with common prefix. In this example queueing "Test1" will queue other folders too.
It happens if you click "Queue All" or if you just drag and drop it.

**Comment by agersant** [comment]
Nice find, this bug must have been here since the dawn of Polaris!
Fixed here: https://github.com/agersant/polaris/pull/79
