### ISSUE TITLE
Bug? with adding new user and auto-complete

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#54]
Polaris 0.12.2
Windows 10, Firefox, Bitwarden with auto-complete

I don't know if it is a bug (but seems like it is, or at least unwanted behaviour), but when I want to create new user, Bitwarden (password manager) auto-completes fields with my credentials. Because Polaris auto-saves user settings, it automatically degrades me from admin to normal user, (because that's the default behaviour) and I am unable to go back. Only fix is to have backup of database or just edit it with e.g. DB Browser.

**Comment by agersant** [comment]
Tentatively disabled autofill in 8bc04d0c0950e468f6b86fd7384a9a885b1d1aa3

**Comment by agersant** [comment]
Fixed in release `0.12.3`!

https://github.com/agersant/polaris/releases/tag/0.12.3
