### ISSUE TITLE
Password auth broken with certain special characters

### ISSUE THREAD

**Issue by vosscodes** [agersant/polaris-web#59]
Polaris 0.12.3, from the linked docker-polaris repo
Tested on MacOS/Windows/Android with latest Firefox/Chrome

When logging into polaris-web, some special characters are getting urlencoded in passwords and breaking auth for any account using them. 
`bl$ah` -> `"password": "bl%24h"`
`bl%ah` -> `"password": "bl%25h"`
`bl!ah` -> `"password": "bl!ah"`

Hitting the api directly works as expected, so those characters are properly making it into the db during [initial setup](https://github.com/agersant/polaris-web/blob/master/src/components/initial-setup/initial-setup.vue#L79).

**Comment by agersant** [comment]
Thank you for the report!

I just fixed this in b558c69f945a1c82128f79d73637bf2f42913442
