### ISSUE TITLE
Feature request: remember track playing position upon page reload

### ISSUE THREAD

**Issue by vvrein** [agersant/polaris-web#61]
Thanks for great UI!
And I though it would be useful in case of long tracks, f.e. 1-2-3h to store current playing position upon browser restart and/or page reload.  

I was able to seek from console like:
`document.getElementsByTagName("Audio")[0].fastSeek(65)` 
but this is where my knowledge ends 😂

**Comment by agersant** [comment]
Thanks for the kind words and for the good suggestion. I'm not sure why I didn't think about doing this one before!

I just implemented it in 4ed685f62509309a74e73b7f32e96de20bd2a863 so it will be in the next Polaris release.
