### ISSUE TITLE
Feature request: Queue specific disc

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#65]
After you told me about the disc feature in #62, I noticed it would be nice to have ability to queue only specific disc.

Maybe already existing label "Disc N" could be drag and dropped onto queue playlist just like albums. Or there could be some button "Queue Disc N" or something like that next to this label. You could even throw some icon with CD before label so it would be more visible (there is "album" icon in material icons).

![image](https://user-images.githubusercontent.com/54780569/90761439-b2984a80-e2e3-11ea-9def-5ff07848bf90.png)

**Comment by agersant** [comment]
Good idea! I tried various permutations of the icon and the button, but I thought they looked too busy. I settled on this version:

![image](https://user-images.githubusercontent.com/817256/90861834-49dfbb00-e341-11ea-9d0c-1bff97cb793d.png)

Submitted as  09ce9a8 and will be in the next release.
