### ISSUE TITLE
Fixing build troubles with new nodejs (npm run production)

### ISSUE THREAD

**Issue by vvrein** [agersant/polaris-web#66]
I have been trying to compile front-end by my own, and I was stuck at `Cannot read property 'length' of undefined`
This issue could be safe closed, I think, and created rather for those who faced the same trouble with new nodejs :)

My env:
- Arch Linux
- npm -v  => 6.14.7
- node -v => v14.8.0

Fail steps:
1) git clone https://github.com/agersant/polaris-web.git
2) cd polaris-web
3) npm install
4) npm run production

Resulted in:
(There was many warnings too, but as for me - they doesn't as important as this, since even after some Voodoo magic, I was able to completely take away warnings, but not this error)
```
🚨  Cannot read property 'length' of undefined
    at lineCounter (/home/polaris/polaris-web/node_modules/parcel/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/home/polaris/polaris-web/node_modules/parcel/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/home/polaris/polaris-web/node_modules/parcel/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/home/polaris/polaris-web/node_modules/parcel/src/Bundle.js:250:5)
    at async Bundle._package (/home/polaris/polaris-web/node_modules/parcel/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/home/polaris/polaris-web/node_modules/parcel/src/Bundle.js:202:5)
    at async Promise.all (index 5)
    at async Bundle.package (/home/polaris/polaris-web/node_modules/parcel/src/Bundle.js:202:5)
    at async Bundler.bundle (/home/polaris/polaris-web/node_modules/parcel/src/Bundler.js:325:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polaris-web@1.0.0 production: `parcel build index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the polaris-web@1.0.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/polaris/.npm/_logs/2020-08-26T05_56_02_794Z-debug.log
```

Logfile /home/polaris/.npm/_logs/2020-08-26T05_56_02_794Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'production' ]
2 info using npm@6.14.7
3 info using node@v14.8.0
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle polaris-web@1.0.0~preproduction: polaris-web@1.0.0
6 info lifecycle polaris-web@1.0.0~production: polaris-web@1.0.0
7 verbose lifecycle polaris-web@1.0.0~production: unsafe-perm in lifecycle true
8 verbose lifecycle polaris-web@1.0.0~production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/polaris/polaris-web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/vrein/.bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle polaris-web@1.0.0~production: CWD: /home/polaris/polaris-web
10 silly lifecycle polaris-web@1.0.0~production: Args: [ '-c', 'parcel build index.html' ]
11 silly lifecycle polaris-web@1.0.0~production: Returned: code: 1  signal: null
12 info lifecycle polaris-web@1.0.0~production: Failed to exec production script
13 verbose stack Error: polaris-web@1.0.0 production: `parcel build index.html`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid polaris-web@1.0.0
15 verbose cwd /home/polaris/polaris-web
16 verbose Linux 5.8.2-arch1-1
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
18 verbose node v14.8.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error polaris-web@1.0.0 production: `parcel build index.html`
22 error Exit status 1
23 error Failed at the polaris-web@1.0.0 production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And I was able to "fix" this with running 
`npm install @babel/helper-compilation-targets --save-dev` 
i.e.
1) git clone https://github.com/agersant/polaris-web.git
2) cd polaris-web
3) npm install
4) npm install @babel/helper-compilation-targets --save-dev
5) npm run production

Also `rm -rf ./.cache` may be needed.

https://stackoverflow.com/questions/62246824/error-err-package-path-not-exported-no-exports-main-resolved-in-app-node-m

**Comment by agersant** [comment]
Thanks for the report and the detailed steps!

I was able to reproduce this issue on my dev machine (Windows) after installing a more recent version of nodejs. I tried 12.18.3 and 14.8.0 (LTS and current), they both had this problem.

Reverting to Node 12.14.1 made the issue go away. I also wiped `.cache` and `node_modules` after installing a different nodejs version. This would be my recommended workaround for now.

Going to keep this issue open as eventually I would like to make things to work out of the box with recent versions of nodejs too.

**Comment by vvrein** [comment]
Hi! Can you help with some compilation issues?
I've compiled polaris-web with steps above, but js code doesn't looks like compiled... Or it just doesn't minified?

I put compiled code here https://github.com/vvrein/compiled-polaris-web
Same code with nodejs-14.12.0 or nodejs-lts-erbium-12.18.3...


I looked into build.yaml, but didn't find anything significant:
```
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.1'
    - name: Build Polaris Web
      run: npm install && npm run production
    - name: Run Automated Tests
      uses: cypress-io/github-action@v1
      with:
        wait-on: 'http://localhost:5050'
```

Here is the browser error:
![image](https://user-images.githubusercontent.com/17022100/94336613-24536a80-ffed-11ea-8d2b-4441cbf8e621.png)
So my main question is how I can got same code as yours? :)

**Comment by agersant** [comment]
This work is somewhat blocked by upgrading to Parcel 2 and Vue 3. Parcel 2 now fully supports Vue 3, but Vue 3 supporting libraries are still in beta. See https://v3.vuejs.org/guide/migration/introduction.html#supporting-libraries

**Comment by crabvk** [comment]
I think this is the issue https://github.com/parcel-bundler/parcel/issues/2957
Try to exclude `.cache` from releases.

**Comment by agersant** [comment]
Following-up: https://github.com/vuejs/docs-next/issues/931
