### ISSUE TITLE
Bug: Administrator setting is broken

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#78]
So I just installed Polaris 0.13.1 and looked at users settings panel.

What caught my attention was that admin checkbox was not checked for me, when I was the only user. It seems that [this line](https://github.com/agersant/polaris-web/blob/0029ed5b8dd6dc09a8b6af6f651828ee9bb2902e/src/components/settings/sections/user.vue#L8) sets checkbox `value` field instead of `checked`.

Then I created test user and gave him admin rights. And as expected when I logged in with this test account he didn't have admin rights.

I don't know vue, but it guess that changing from `v-bind:value="user.is_admin"` to `v-bind:checked="user.is_admin"` should solve this.

**Comment by agersant** [comment]
Good find!
Fixed in 5aca2ba8bee5ab1917108b002e3dfa1a598daf82
