### ISSUE TITLE
Bug: Multi-disc album details (content) displayed and queued incorrectly

### ISSUE THREAD

**Issue by michalsieron** [agersant/polaris-web#79]
I am aware that display part of this issue is caused by implemented solution to #67, yet after declaration from 0.13.0 changelog ("Individual discs from multi-disc albums can now be dragged into the playlist.") I think it is causing this bug.

When you have multi-disc album it gets displayed like this - sorted alphabetically.
![image](https://user-images.githubusercontent.com/54780569/103176359-f3dbd080-4868-11eb-9fd6-554dfe5f53d3.png)

When you try do drag one of these "part-disks" onto playlist pane (e.g. this one)
![image](https://user-images.githubusercontent.com/54780569/103176487-f0951480-4869-11eb-8f0a-e5fc29c69857.png)
it only adds songs from that "part-disk" (in this case only those 2 songs, while disk contains 15 songs).

Polaris 0.13.1, Windows 10, Firefox 84

**Comment by agersant** [comment]
Also a good find, thanks for the report!

Fixed in bc85bcffbe0603c8159b135c3d7e3137c8cded04 (and apologies about the borked display you have to put up with until semantic browsing gets implemented)

**Comment by michalsieron** [comment]
Thanks for quick fix. And I understand that the display issue isn't that big of a deal as multi-disc albums are not that common, so don't worry about that one.

**Comment by agersant** [comment]
I made a minor release with this fix in case you want to get your hands on it (and the user settings one too).
