### ISSUE TITLE
Playlist view gets clipped when the window is tall enough

### ISSUE THREAD

**Issue by jansol** [agersant/polaris-web#81]
Case in point: 
![image](https://user-images.githubusercontent.com/2588851/109575725-0ee1ef80-7afb-11eb-9ab5-9cd00ac7c87c.png)

As you can guess from the duration at the top (btw a day count would be nice :wink: ) the playlist is a lot longer than can be shown in the window,  yet the visible area of the playlist gets clipped. The empty space is not clickable either so it would seem there are no invisible elements.

Upon further experimentation, it seems the playlist view is limited to a certain number of *elements* and not space since elements at the bottom pop in and out of view instead of sliding. If that is indeed the case, adjusting this number on the fly would solve the problem.

**Comment by agersant** [comment]
Good find. The view is limited to 50 entries and that is a very questionable limitation. Will fix before next release (although that's a while away, I'm on a polaris hiatus at the moment).

**Comment by agersant** [comment]
Fixed in https://github.com/agersant/polaris-web/pull/83

**Comment by agersant** [comment]
Also added the playlist duration in days while I was there.
https://github.com/agersant/polaris-web/pull/84
