### ISSUE TITLE
Inconsistent year display

### ISSUE THREAD

**Issue by jansol** [agersant/polaris-web#88]
Some albums show a year in the "latest additions" and "random" views, some don't. Should possibly use Date or Originaldate tags in addition to Year.

**Comment by agersant** [comment]
Good point. This shouldn't be too hard to add to the metadata parsing code at some point.

Reference: https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping#Dates

**Comment by agersant** [comment]
Upstream PR (pending release): https://github.com/polyfloyd/rust-id3/pull/105

**Comment by agersant** [comment]
Added in https://github.com/agersant/polaris/commit/a8660793f8331599435ec5d71f4788894a374d86
