### ISSUE TITLE
Playback problem

### ISSUE THREAD

**Issue by jansol** [agersant/polaris-web#89]
I have one album that consistently fails to play any of its tracks, despite working fine in mpd. Debugging tools show 2.50MB responses with code 204 Partial Content for the relevant requests and the console logs an error "media could not be decoded". Files are flac (as are most of the working ones).

**Comment by lnicola** [comment]
Can you upload one of those files somewhere? Or at least paste the output of `ffprobe`.

Even a e.g. 1 second extract might help if the issue still occurs.

**Comment by jansol** [comment]
I tried copying a short bit of a failing file to a new one with ffmpeg, but the resulting file was working fine. The only difference between the only working track in the album and the others when checking ffprobe is that the working file has the ENCODER and ENCODED-BY tags written, in the others it is empty.

However upon closer inspection it seems that for some reason the web frontend is requesting a range that doesn't start at 0 when attempting to play one of the failing tracks (no seeking, just clicking a track from the playlist). The starting point seems arbitrary and changes between problematic tracks, but remains consistent for any given track across multiple play attempts even when reloading the page or restarting the polaris daemon.

**Comment by lnicola** [comment]
There is no web front end that requests audio data. Polaris uses HTML5 audio, so the same thing should happen with a static page that loads one of the songs. Last time I ran into this, it was a browser bug.

**Comment by jansol** [comment]
Right. I managed to repro the problem with `python -m http.server` and a html page with only an audio element pointing to the file so it clearly isn't related to polaris.

**Comment by jansol** [comment]
Randomly looked at the hexdump of a problematic file and it started making a lot more sense: it's actually an ID3 container with FLAC data inside. Applications that only look at the first few bytes to decide the type find an (empty) ID3 container and conclude that there is nothing to see. "simpler" applications just see the filename ending in .flac and feed it to the flac decoder (which knows to skip extra stuff in the stream) and everything is fine. Fancier applications would scan the file and notice that it has a flac header after the ID3 block and decode from there.

This is sort of a valid thing to do, and the reference flac decoder handles it gracefully but at the same time [the FLAC FAQ](https://www.xiph.org/flac/faq.html#general__tagging) mentions that one should not expect it to work and that it may cause applications to fail to decode the file/stream at all.
