### ISSUE TITLE
Logarithmic Volume Control

### ISSUE THREAD

**Issue by pbsds** [agersant/polaris-web#93]
Human perception of loudness is logarithmic, not linear. As such, most volume controls cater to the human ear using logarithmic scaling. ([source](https://techsupport.cambridgeaudio.com/hc/en-us/articles/360000105437-Amplifiers-Linear-Logarithmic-Volume-Control), and [an other source](https://dcordero.me/posts/logarithmic_volume_control.html))

Could this be added to polaris-web?

**Comment by agersant** [comment]
Good suggestion! I will implement this eventually.

**Comment by agersant** [comment]
Added in 5b5103008e676e50597919aa129fb3e3539916bc
